### ISSUE TITLE
Plugin causes problem in Menu settings

### ISSUE THREAD

**Issue by s4ndr0wy** [piotr-urbanowicz/woo-payments-by-shipping#3]
Hi there,

The plugin is causing problems in my Appearance > Menu settings. When it is activated I cannot change anything in menus (they dissapear) but the website is working properly.

When I deactivate the plugin I can do changes. See screenshots. Hope you can help :)

Im using:
Wordpress 4.9.4
Woocommerce 3.3.4
and Precise theme:
https://themeforest.net/item/precise-a-modern-minimalistic-shop-theme/20271127

<img width="1135" alt="zrzut ekranu 2018-03-28 o 10 16 57" src="https://user-images.githubusercontent.com/37864183/38017037-316aa2fc-3271-11e8-8ae9-1c10ea8c40d2.png">

**Comment by piotr-urbanowicz** [comment]
Thanks for your feedback, issue have been fixed: https://github.com/piotr-urbanowicz/woo-payments-by-shipping/commit/1fdcace0da08f1d5621213efecb02c1f067b697e, please download new version of the plugin and check again.
